/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sk.skog.users;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import sk.skog.users.command.action.CommandTest;
import sk.skog.users.command.queue.CommandConsumerTest;
import sk.skog.users.command.queue.SampleCommandProducerTest;
import sk.skog.users.data.UserTest;
import sk.skog.users.service.PersistenceServiceTest;

@RunWith(Suite.class)
@SuiteClasses({
	CommandTest.class,
	CommandConsumerTest.class,
	SampleCommandProducerTest.class,
	UserTest.class,
	PersistenceServiceTest.class })
public class AppTest {

}
